---
- name: Configure dotfiles
  hosts: localhost
  vars:
    path_app_conf: "{{ playbook_dir }}/appconf"
    path_bashrc: "~/.bashrc"
    ssh_config_path: "~/.ssh/config.d"
    path_ssh_conf: "~/.ssh/"
    path_private_local: "~/.config/private_local"
    ncspot_dir: "~/.var/app/io.github.hrkfdn.ncspot/config/ncspot/"
  tasks:
    - name: "Base configuration"
      tags:
        - always
      ansible.builtin.import_tasks: ./tasks/base.yml

    - name: "SSH configuration"
      tags:
        - always
      ansible.builtin.import_tasks: ./tasks/ssh.yml

    - name: "Gnome keybindings"
      tags:
        - always
      ansible.builtin.import_tasks: ./tasks/gnome_keybindings.yml

    - name: "Ptyxis configurations"
      tags:
        - always
      ansible.builtin.import_tasks: ./tasks/terminal.yml

    - name: "Install sw from external repository"
      tags:
        - never
      ansible.builtin.import_tasks: ./tasks/external_repo.yml

    - name: "Install sw from flatpak"
      tags:
        - never
      ansible.builtin.import_tasks: ./tasks/flatpak.yml

  handlers:
    - name: "Handlers for flatpak tasks"
      ansible.builtin.import_tasks: ./handlers/flatpak.yml

    - name: App conf
      loop:
        - path: "~/.config/glow"
          src: "{{ path_app_conf }}/glow"
      ansible.builtin.file:
        path: "{{ item.path }}"
        src: "{{ item.src }}"
        state: link
