---
- hosts: localhost
  vars:
    path_bashrc: "~/.bashrc"
    ssh_config_path: "~/.ssh/config.d"
    path_ssh_conf: "~/.ssh/"
    path_private_local: "~/.config/private_local"

  tasks:
    - name: "Create private_local"
      file:
        path: "{{ path_private_local }}"
        state: directory

    - name: "Install bashrc"
      file:
        path: "{{ path_bashrc }}"
        src: "{{ playbook_dir }}/bashrc"
        state: link

    - name: "Create config.d"
      file:
        path: "{{ ssh_config_path }}"
        state: directory

    - name: "Install ssh config"
      file:
        path: "{{ path_ssh_conf }}/config"
        src: "{{ playbook_dir }}/ssh_config"
        state: link
        mode: '600'

    - name: "Install ncspot"
      flatpak:
        name: io.github.hrkfdn.ncspot
        state: latest
        remote: flathub
      tags:
        - never
        - application
        - ncspot
      notify:
        - Conf ncspot

  handlers:
    - name: Conf ncspot
      copy:
        dest: "~/.var/app/io.github.hrkfdn.ncspot/config/ncspot/config.toml"
        src: "{{ playbook_dir }}/appconf/ncspot/config.toml"
        remote_src: true
        force: true
