---

        - name: "Install Ncspot"
          community.general.flatpak:
            name:
              - io.github.hrkfdn.ncspot
              - io.gitlab.librewolf-community
              - net.cozic.joplin_desktop
              - io.freetubeapp.FreeTube
            state: latest
            remote: flathub
          notify:
            - Ncspot dir
            - Ncspot conf

