---

- name: "Install Ncspot"
  tags:
    - never
    - ncspot
  community.general.flatpak:
    name:
      - io.github.hrkfdn.ncspot
    state: latest
    remote: flathub

- name: Ncspot dir
  tags:
    - ncspot
    - never
  ansible.builtin.file:
    path: "{{ ncspot_dir }}"
    state: directory

- name: Ncspot conf
  tags:
    - ncspot
    - never
  ansible.builtin.copy:
    dest: "{{ ncspot_dir }}/config.toml"
    src: "{{ playbook_dir }}/appconf/ncspot/config.toml"
    remote_src: false
    force: true


- name: "Install FreeTube"
  tags:
    - never
    - FreeTube
  community.general.flatpak:
    name:
      - io.freetubeapp.FreeTube
    state: latest
    remote: flathub

- name: "Install Joplin"
  tags:
    - never
    - joplin
  community.general.flatpak:
    name:
      - net.cozic.joplin_desktop
    state: latest
    remote: flathub

- name: "Install Librewolf"
  tags:
    - never
    - librewolf
  community.general.flatpak:
    name:
      - io.gitlab.librewolf-community
    state: latest
    remote: flathub
